### PR TITLE
docs: fix `typedoc` compilation warnings

### LINKED ISSUE #749: docs: fix `typedoc` warnings and outdated tsdoc comments
Generating the docs produce some warning:
`yarn docs`

```
[info] Converting project at ./packages/core
[warning] No entry points were provided, this is likely a misconfiguration.
[info] Converting project at ./packages/data
[info] Converting project at ./packages/group
[warning] The signature Group.import has an @param with name "nodes", which was not used.
[info] Converting project at ./packages/heyauthn
[info] Converting project at ./packages/identity
[info] Converting project at ./packages/proof
[info] Converting project at ./packages/utils
[warning] The signature getDeployedContract has an @param with name "The", which was not used.
[info] Merging converted projects
[info] Documentation generated at ./docs
```

### PR DESCRIPTION
**Pull request by sripwoud**
Fix different warnings shown when building the docs.

Fixes #749

## Test plan
|Before|After|
|--|--|
|`yarn docs`: builds successfully but generates a bunch of warnings|`yarn docs`: builds successfully without warnings|

### CODE REVIEW

File: packages/group/src/index.ts [hunk 1]
```diff
@@ -144,10 +144,10 @@ export class Group {
      * @param nodes The stringified JSON of the group.
      * @returns The {@link Group} instance.
      */
-    static import(exportedGroup: string): Group {
+    static import(nodes: string): Group {
```
Comment (sripwoud) [inline packages/group/src/index.ts:147]: to decide whether to use `nodes` or `exportedGroup`, I chose to reuse what is in `@zk-kit/imt`

https://github.com/privacy-scaling-explorations/zk-kit/blob/8f37c779dae20f13a7a31cc7bed0728b6a07d52c/packages/imt/src/lean-imt/lean-imt.ts#L336

File: typedoc.js
Comment (sripwoud) [inline typedoc.js:1]: Turning typedoc.json into a js file is a mirror from https://github.com/privacy-scaling-explorations/zk-kit/pull/260

**Review by cedoor — APPROVED** [review]
